<?php
declare(strict_types=1);

namespace Squareetlabs\LaravelPdfToHtml\Support;

use RecursiveIteratorIterator;
use RecursiveDirectoryIterator;
use FilesystemIterator;

/**
 * Class Base
 * @package Squareetlabs\PdfToHtml
 */
class Base
{
    /** @var string */
    private $outputDir = '';

    /** @var array */
    private $options = [];

    /**
     * Get all options or one option by key.
     * @param string|null $key
     * @return mixed
     */
    public function getOptions(?string $key = null)
    {
        if ($key) {
            return $this->options[$key] ?? null;
        }
        return $this->options;
    }

    /**
     * Set options as array or pair key-value.
     * @param array|string $key
     * @param mixed $value
     */
    public function setOptions($key, $value = null): void
    {
        if (is_array($key)) {
            $this->options = array_replace_recursive($this->options, $key);
        } elseif (is_string($key)) {
            $this->options[$key] = $value;
        }
    }

    /**
     * Get output dir.
     * @return string
     */
    public function getOutputDir(): string
    {
        return $this->outputDir;
    }

    /**
     * Set output dir.
     * @param string $dir
     * @return $this
     */
    public function setOutputDir(string $dir)
    {
        $this->setOptions('outputDir', $dir);
        $this->outputDir = $dir;
        return $this;
    }

    /**
     * Clear all files that has been generated by pdftohtml.
     * @param bool $removeSelf
     * @return $this
     */
    public function clearOutputDir(bool $removeSelf = false)
    {
        if (!is_dir($this->getOutputDir())) {
            return $this;
        }

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($this->getOutputDir(), FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $file) {
            $path = $file->getRealPath();
            if ($file->isDir()) {
                rmdir($path);
            } else {
                unlink($path);
            }
        }

        if ($removeSelf) {
            rmdir($this->getOutputDir());
        }

        return $this;
    }
}
?>